# show user prefix of data Summry
GET  http://localhost:3001/person/34
#show user group detal 
GET http://localhost:3001/person/getPersonCategory/33
# show user Quastion And Answr on Each Quastion
GET http://localhost:3001/person/getPersonQuastionDetail/33
# reply on click for quastion
GET http://localhost:3001/person/getPersonAnsweredQuastion/137
# Answed By person
GET http://localhost:3001/person/getPersonAnsweredDetail/33
# person Follower
GET http://localhost:3001/person/getPersonFollowerDetail/33
# person Following
GET http://localhost:3001/person/getPersonFollowingDetail/33



 






